name: "Fantasy Football"

on:
  push:
    branches: [ "ci-test" ]
  schedule:
  - cron: "0 12 * * *"

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        #token: ${{ secrets.CI_TOKEN }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install Project and Applications
      run: |
        python -m pip install . --upgrade
    - name: Setup SSH
      run: |
        mkdir ~/.ssh

        # add the private key for use
        echo ${{ secrets.SSH_PRIVATE_KEY }} >> ~/.ssh/id_rsa

        # Add github to the known hosts
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

        # set the permissions in the .ssh directory to the expected
        chmod -R 600 ~/.ssh

    - name: Setup Git
      run: |
        git config --global user.name "Brent Barbachem"
        git config --global user.email "barbacbd@dukes.jmu.edu"

    - name: Execute the Applications
      run: |
        cd docs;

        # this should create several files including Markdown and XLSX files
        FantasyProsFF

        # Excute the program to combine all data into the readme file
        FFReadme

        # Move the altered readme to the main page
        mv README.md ..

        cd ..;
        git add README.md
        git add docs

        git commit -m "[Automated Commit]: Updating fantasy football information."
        git push --force
